version: "3.6"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./:/code"
      - "./.docker/nginx:/etc/nginx/conf.d/"
    links:
     - phpfpm

  phpfpm:
    build:
      context: ./.docker/phpfpm
    volumes:
      - "./:/code"
    links:
      - db
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf-bootstrap
    ports:
    - "3307:3306"

#  nodejs:
#    build:
#      context: ./.docker/nodejs
#    volumes:
#      - "./:/code"

  browser:
    hostname: browser
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"